#!/usr/bin/env bash

AWS_ACCOUNT_ID=$1

if [ -z $AWS_ACCOUNT_ID ];
then
    echo "No input, this requires an AWS account ID"
    exit 1
else
    AC_NAME=$(grep $AWS_ACCOUNT_ID ~/.aws/config -B1 | grep profile | cut -d " " -f 2 |sed 's/\]//g')
    export AWS_PROFILE=$AC_NAME
    saml2aws login --skip-prompt --force --role arn:aws:iam::${AWS_ACCOUNT_ID}:role/ADFS-CloudRO
fi
