#!/bin/bash

kubectl get pods --all-namespaces | grep Evicted | $(awk '{print "kubectl -n " $1 " delete pod "$2}')
kubectl get pods --all-namespaces | grep Error | $(awk '{print "kubectl -n " $1 " delete pod "$2}')
