#!/bin/bash

find . -type d -name '.git' | grep -v '\.terraform' | cut -d/ -f2-3 | xargs -I{} bash -c "cd {};echo {};git branch -rv | grep renovate | grep -v 'update helm release'" | grep -v 'origin/master' | less
